name: Maven Build

on:
  push:
  workflow_dispatch:

jobs:
  Palladio-Core-Commons:
    runs-on: self-hosted
    steps:
      - uses: Nicolas-Boltz/BuildPipelineActionTest@v2
        with:
          use-display-output: true
          deploy-updatesite: 'Core-Commons'

