name: Maven Build

on:
  push:
  workflow_dispatch:

jobs:
  Palladio-Core-Commons:
    runs-on: self-hosted
    steps:
      - uses: Nicolas-Boltz/BuildPipelineActionTest@main
        with:
          build-repository: PalladioSimulator/Palladio-Core-Commons
          use-display-output: true
          deploy-updatesite: releng/org.palladiosimulator.core-commons.updatesite/target/repository

