name: Maven Build

on:
  push:
  workflow_dispatch:

jobs:
  Palladio-Core-Commons:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: PalladioSimulator/Palladio-Core-Commons
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11 
          cache: 'maven'
      - name: Verify with Maven
        run: DISPLAY=:0 mvn clean verify
  
